"use client";

import { useState } from "react";
import { useForm } from "react-hook-form";
import * as z from "zod";
import { zodResolver } from "@hookform/resolvers/zod";

import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";

const formSchema = z.object({
  name: z.string().min(2, { message: "Name must be at least 2 characters." }),
  agree: z.literal(true, {
    errorMap: () => ({ message: "You must agree to the terms and conditions." }),
  }),
});

export default function TermsPage() {
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  
  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      name: "",
      // Don't set a default value for agree since it must be true
    },
  });

  async function onSubmit(values: z.infer<typeof formSchema>) {
    setIsSubmitting(true);
    
    try {
      // Formspree submission (replace with actual endpoint)
      const response = await fetch("https://formspree.io/f/yourformid", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          name: values.name,
          agreedToTerms: values.agree,
          date: new Date().toISOString(),
        }),
      });
      
      if (response.ok) {
        setIsSubmitted(true);
        form.reset();
      } else {
        throw new Error("Form submission failed");
      }
    } catch (error) {
      console.error("Error submitting form:", error);
      alert("There was an error submitting your agreement. Please try again.");
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <main className="flex min-h-screen flex-col items-center">
      {/* Header section */}
      <section className="w-full py-16 bg-blue-100">
        <div className="max-w-4xl mx-auto px-4 text-center">
          <h1 className="text-4xl md:text-5xl font-bold text-blue-900 mb-4">Terms and Conditions</h1>
        </div>
      </section>

      {/* Terms content */}
      <section className="w-full py-12 px-4 bg-white">
        <div className="max-w-3xl mx-auto">
          <div className="prose prose-blue max-w-none">
            <p>
              Blue Waters is our home away from home and we choose to share it with friends and others. 
              When we rent it out to other people, there is a lot of trust involved on our part. We are 
              sure you will want to look after our home but want to formalise our agreement so we have 
              a mutual understanding. Please read the following and sign/date at the bottom.
            </p>
            
            <p>
              The owners of Blue Waters Villa, cannot be held responsible for any loss or injury to 
              persons or property which may occur on or in the vicinity of the property.
            </p>
            
            <p>
              <strong>Insurance</strong> – It is highly recommended that guests take out comprehensive 
              insurance prior to travel to cover the cancellation of your trip, medical emergencies and 
              your personal effects whilst staying at the property.
            </p>
            
            <p>
              <strong>Damage</strong> – You are responsible for the property and its contents during your stay. 
              Any damage or loss above normal wear and tear will be deducted from your deposit at the local 
              replacement price. Please notify the Property Manager should anything get lost, damaged or broken 
              during your stay.
            </p>
            
            <h2 className="text-2xl font-bold text-blue-900 mt-8 mb-4">Booking</h2>
            
            <p>
              50% of the total rental price is payable on booking. The remaining 50% is due 8 weeks before 
              your arrival. Unfortunately we are unable to hold your reservation if payment is not made by 
              the due date. We are happy to accept payment by PayPal or direct bank transfer in USD, CAD or GBP. 
              If you would like to use PayPal we will need to add the 4% fee they charge us to your total.
            </p>
            
            <h2 className="text-2xl font-bold text-blue-900 mt-8 mb-4">Electricity</h2>
            
            <p>
              Electricity is very expensive in Barbados as (unfortunately) it is generated by burning bunker oil. 
              It costs 3-5 times what we would pay in Canada, the US or the UK. The AC units in the bedrooms, 
              clothes dryer, dishwasher and hot water tank are efficient but are the biggest users of electricity. 
              Your weekly rate at Blue Waters Villa includes 100 kilowatt hours per 2 people which is more than 
              enough electricity for normal use.
            </p>
            
            <p>In real terms this means you can:</p>
            
            <ul className="list-disc pl-6 space-y-2">
              <li>
                run the AC units in the occupied bedrooms at night but not all day or with the windows open. 
                There are ceiling fans in all rooms which is how most Bajans keep cool.
              </li>
              <li>
                use the dryer a couple of times during the week. Things dry really quickly on the clotheslines 
                outside or drying rack inside if you care to use them.
              </li>
              <li>use a reasonable amount of hot water.</li>
              <li>generally turn off lights and other things when you don&apos;t need them.</li>
            </ul>
            
            <p>
              If you need more electricity than roughly what is described above, then no problem! Our Property 
              Manager will read the meter on your arrival and again when you depart. If you need more than the 
              amount described above, you&apos;ll simply pay for each additional kilowatt hour at our cost. We do not 
              mark this up.
            </p>
            
            <h2 className="text-2xl font-bold text-blue-900 mt-8 mb-4">Additional Fees</h2>
            
            <ul className="list-disc pl-6 space-y-2">
              <li>Call out to reset safe code / locked out of safe - $50 USD</li>
              <li>Replace lost house key or locked out - $50 USD</li>
            </ul>
            
            <h2 className="text-2xl font-bold text-blue-900 mt-8 mb-4">Changes to your confirmed booking</h2>
            
            <p>
              If you wish to cancel your vacation within 48 hours of booking, your deposit will be refunded in 
              full less an administration fee of $100 USD. If you wish to cancel or change dates, please contact 
              us via e-mail and we will do our best to accommodate your request but do not guarantee we will be 
              able to. An amendment fee may be applicable.
            </p>
            
            <p>
              <strong>Arrival and Departure</strong> – Check-in time is at 4pm and Check-out time is at 11am 
              unless requested otherwise at the time of booking. If you would like to check in earlier or leave 
              later, we will do our best to accommodate you unless we have other guests arriving or leaving on 
              the same day. If you fail to arrive by noon on the day after your arrival date without contacting 
              the Property Manager or us, we may treat the booking as cancelled and will not be responsible for 
              refunding any fees already paid.
            </p>
            
            <h2 className="text-2xl font-bold text-blue-900 mt-8 mb-4">Accommodation and Behaviour</h2>
            
            <p>
              While staying in our home, it is important you show consideration for neighbours and the property 
              itself. If you or your party appear to be conducting yourselves in a way deemed inappropriate, for 
              example causing annoyance, distress, danger to others or damage to the property, we reserve the right 
              to terminate your holiday arrangements, without refund or compensation.
            </p>
            
            <p>You agree not to smoke, nor to allow smoking inside the property at any time.</p>
            
            <p>
              The property is reserved exclusively for you and those listed on the booking form. No additional 
              persons, unless agreed in writing with us or the Property Manager, are permitted to stay in the 
              accommodation.
            </p>
            
            <p>
              No parties, weddings or events of any kind shall be held in our home during your stay without the 
              prior agreement of ourselves or the Property Manager. Should any such gathering take place, the 
              Property Manager has the right to remove occupants from the property without refund or compensation.
            </p>
            
            <p>
              Our maximum liability for losses you suffer as a result of us acting in breach of these terms and 
              conditions is strictly limited to the total fees you have paid for the Booking. We shall not be 
              liable for any losses that are not a foreseeable consequence of us breaking these Booking Conditions. 
              Losses are foreseeable where they could be contemplated by you and us at the time your Booking is 
              confirmed by us. We shall not be liable to you for any accident, personal injury or damage to or 
              loss of personal property.
            </p>
            
            <h2 className="text-2xl font-bold text-blue-900 mt-8 mb-4">Payment</h2>
            
            <p>
              I agree to forward payment of the remaining balance eight weeks prior to the letting or earlier. 
              Your damage and electricity deposit will be returned to you within 1 week of vacating the property.
            </p>
            
            <p>
              I have read the Agreement above and accept it as part of this booking contract. I am over 25 years 
              of age and accept that my booking is for the holiday period stated above. I am willing to accept 
              responsibility for any breakages and will vacate the property at the conclusion of the period above 
              as agreed.
            </p>
          </div>

          {/* Agreement form */}
          <div className="mt-12 p-6 bg-blue-50 rounded-lg shadow-sm">
            <h3 className="text-xl font-semibold text-blue-900 mb-6">Agreement to Terms</h3>
            
            {isSubmitted ? (
              <div className="bg-green-50 text-green-700 p-6 rounded-lg text-center">
                <h3 className="text-xl font-semibold mb-2">Thank you!</h3>
                <p>Your agreement to our terms and conditions has been recorded.</p>
              </div>
            ) : (
              <Form {...form}>
                <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
                  <FormField
                    control={form.control}
                    name="name"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Full Name</FormLabel>
                        <FormControl>
                          <Input placeholder="Enter your full name" {...field} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  
                  <FormField
                    control={form.control}
                    name="agree"
                    render={({ field }) => (
                      <FormItem className="flex flex-row items-start space-x-3 space-y-0 rounded-md border p-4">
                        <FormControl>
                          <Checkbox
                            checked={field.value}
                            onCheckedChange={field.onChange}
                          />
                        </FormControl>
                        <div className="space-y-1 leading-none">
                          <FormLabel>
                            I have read and agree to the terms and conditions above
                          </FormLabel>
                        </div>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  
                  <Button 
                    type="submit" 
                    className="w-full" 
                    size="lg"
                    disabled={isSubmitting}
                  >
                    {isSubmitting ? "Submitting..." : "Submit Agreement"}
                  </Button>
                </form>
              </Form>
            )}
          </div>
        </div>
      </section>
    </main>
  );
}